a = input('digite algo: ')
print ('O tipo primitivo desse valor é ', type(a))
print('Só tem espaço? ', a.isspace())
print('É um numero? ', a.isnumeric())
print('é alfabético', a.isalpha())
print('É alfanumerico ? ', a.isalnum())
print('está em maiusculo', a.isupper())
print('está minuscula', a.islower())
print('está capitalizada', a.istitle())
